# yaml-language-server: $schema=https://json.schemastore.org/yamllint.json
# Name of your application. Used to uniquely configure containers.
service: nginx

# Name of the container image.
image: m32c4/ecr-repository

# Deploy to these servers.
servers:
  web:
    hosts:
      - <%= ENV.fetch('KAMAL_SERVER_IP') %>
    options:
      network: "kamal" # INFO: needs `docker network create kamal` on the servers!

# Credentials for your image host.
registry:
  # Specify the registry server, if you're not using Docker Hub
  server: <%= ENV.fetch('KAMAL_REGISTRY') %>
  username: AWS

  # Always use an access token rather than real password when possible.
  password: <%= ENV.fetch('KAMAL_REGISTRY_PASSWORD') %>

# Inject ENV variables into containers (secrets come from .env).
# Remember to run `kamal env push` after making changes!
# INFO: Uncomment to add mysql to the server
#       Also add all envs as GitHub Environment vars.
# env:
#   secret:
#     - MYSQL_USER
#     - MYSQL_PASSWORD
#     - MYSQL_DATABASE

hooks_path: ./hooks # path relative to where "kamal" command is run!

ssh:
  user: ubuntu
  # keys_only: true
  # keys: ["~/.ssh/id_rsa.pem"]

# Configure builder setup.
builder:
  context: ../
  dockerfile: ../Dockerfile
#   args:
#     RUBY_VERSION: 3.2.0
#   secrets:
#     - GITHUB_TOKEN
#   remote:
#     arch: amd64
#     host: ssh://app@192.168.0.1

# Use accessory services (secrets come from .env).
# INFO: Uncomment to add mysql to the server
#       Also add all envs as GitHub Environment vars.
# accessories:
#   mysql:
#     image: mysql:8.0
#     host: <%= ENV.fetch('KAMAL_SERVER_IP') %>
#     port: 3306
#     env:
#       clear:
#         MYSQL_ROOT_HOST: "%"
#       secret:
#         - MYSQL_ROOT_PASSWORD
#         - MYSQL_USER
#         - MYSQL_PASSWORD
#         - MYSQL_DATABASE
#     options:
#       network: "kamal" # INFO: needs `docker network create kamal` on the servers!
#     directories:
#       - data:/var/lib/mysql

# Configure custom arguments for Traefik. Be sure to reboot traefik when you modify it.
traefik:
  options:
    network: "kamal" # INFO: needs `docker network create kamal` on the servers!
#   args:
#     accesslog: true
#     accesslog.format: json

# Configure a custom healthcheck (default is /up on port 3000)
# healthcheck:
#   path: /healthz
#   port: 4000
healthcheck:
  path: /up
  port: 3000
# Bridge fingerprinted assets, like JS and CSS, between versions to avoid
# hitting 404 on in-flight requests. Combines all files from new and old
# version inside the asset_path.
#
# If your app is using the Sprockets gem, ensure it sets `config.assets.manifest`.
# See https://github.com/basecamp/kamal/issues/626 for details
#
# asset_path: /rails/public/assets

# Configure rolling deploys by setting a wait time between batches of restarts.
# boot:
#   limit: 10 # Can also specify as a percentage of total hosts, such as "25%"
#   wait: 2

# Configure the role used to determine the primary_host. This host takes
# deploy locks, runs health checks during the deploy, and follow logs, etc.
#
# Caution: there's no support for role renaming yet, so be careful to cleanup
#          the previous role on the deployed hosts.
# primary_role: web

# Controls if we abort when see a role with no hosts. Disabling this may be
# useful for more complex deploy configurations.
#
# allow_empty_roles: false
