services:
  nginx:
    build:
      context: . # Muss zum Ordner mit einem Dockerfile zeigen
      dockerfile: dev.Dockerfile
    # image: image # Braucht man nur wenn ein image schon vorhanden ist!
    container_name: nginx
    ports:
      - "3000:3000"
    volumes:
      - ./src/:/usr/share/nginx/html
